* How to name the file I store on S3?
** how to get the name of the uploaded file?
https://github.com/mmcgrana/weld/blob/14a26bf8105f768ede71dfe1724b8d1ea60283fa/src/weld/request.clj#L97
** change "put!" api to include name
* How to create thumbnails?
* Arenas
** Which philosopher would you..
** Which deity would you rather go bowling with?
** Which creature would win in a fight?
Repubs
Dick Cheney
GW Bush
Condaleez Rice
Mitt Romney
Scott Walker
Michelle Bachmann
Newt Gingrich
John McCain
Sarah Palin

Monsters
Zombie
Vampire
Werewolf
Creature from the Black Lagoon
Yeti
Bigfoot
Mummy
Cthulhu
Kraken
Brownie
Goblin

* Multiple arenas
** create short id for arena
** add friend
** allow users to create and admin their own arenas
** home page
modify session to include all pairs shown, keyed by arena id
randomize the arenas shown on the home page
*** if on the home page, always show completely random people
**** in the right column, always show the winner between the two people who were just in main area
*** if on an arena page, always show random fighters from that arena in the main area
**** in the right column, always show the winner between the two people who were just in main area
*** use arena id in URL, send winner as post request. ensure that refreshing doesn't send var again
** when clicking on a battle, continue showing that battle; home page
** somehow pass previous fighters to listing function
